In [5]:
!free -m

              total        used        free      shared  buff/cache   available
Mem:          15043         345       11972          10        2724       14422
Swap:             0           0           0


In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
# !python evaluate_cityscapes.py \
#     --restore-from ./snapshots/1280x640_restore_ft_GN_batchsize9_512x256_pp_ms_me0_classbalance7_kl0_lr1_drop0.2_seg0.5_BN_80_255_0.8_Noaug/GTA5_25000.pth

In [9]:
#!watch -n 0.5 nvidia-smi
#!watch -n 0.5 free -m

In [9]:
!python train_ms.py \
    --restore-from ./aerial_network_training/checkpoints/vary_dropout_2_reduce_variance/latest_lr0.00025_gam2_drop0.00.pth \
    --num-classes 6 \
    --data-list ./dataset/potsdam_list/train.txt \
    --data-dir ./data/potsdam \
    --data-list-target ./dataset/dstl_list/train.txt \
    --data-dir-target ./data/dstl \
    --snapshot-dir baseline_run \
    --droprate 0.1 --batch-size 1 --learning-rate 2e-4 --crop-size 1000,1000 \
    --lambda-seg 0.5  --lambda-adv-target1 0.0002 --lambda-adv-target2 0.001 \
    --lambda-me-target 0  --lambda-kl-target 0.1  \
    --norm-style gn  --class-balance  --only-hard-label 80 \
    --max-value 7  --gpu-ids 0  --often-balance  --use-se --fp16 \
    --num-workers 16 --is-training --save-pred-every 100
# --verbose_model_loading

/opt/conda/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults f

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0000, 2.3711, 1.0000, 1.0000, 1.0000, 2.2352], device='cuda:0')
original loss: 1.658128
original loss: 1.063518
Elapsed time in update: 4.384004
exp = baseline_run
 iter =       12/  100000  loss_seg1 = 1.760 loss_seg2 = 2.256 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 5.812, loss_adv2 = 5.788 loss_D1 = 2.906 loss_D2 = 2.895, val_loss=2.525
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0000,  2.2340,  1.0000,  1.0000, 11.2000,  2.1117], device='cuda:0')
original loss: 1.568222
original loss: 0.973685
Elapsed time in update: 4.387397
exp = baseline_run
 iter =       13/  100000  loss_seg1 = 1.599 loss_seg2 = 2.789 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 5.771, loss_adv2 = 5.741 loss_D1 = 2.885 loss_D2 = 2.872, val_loss=1.622
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0000,  2.1106,  1.0000,  1.0000, 10.7800,  2.0005], device='cuda:0')
original loss: 1.839269

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0000, 12.4965,  1.3937,  1.0000,  1.0901, 15.1236], device='cuda:0')
original loss: 1.919185
original loss: 2.275785
Elapsed time in update: 4.405414
exp = baseline_run
 iter =       31/  100000  loss_seg1 = 2.393 loss_seg2 = 3.647 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.157, loss_adv2 = 1.347 loss_D1 = 1.737 loss_D2 = 1.714, val_loss=1.614
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0000, 16.1468,  1.3543,  1.0000,  1.0811,  2.0445], device='cuda:0')
original loss: 1.623870
original loss: 1.709929
Elapsed time in update: 4.370181
exp = baseline_run
 iter =       32/  100000  loss_seg1 = 1.922 loss_seg2 = 3.294 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.347, loss_adv2 = 1.541 loss_D1 = 1.670 loss_D2 = 1.647, val_loss=2.042
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0000, 2.1760, 1.3189, 1.0000, 1.0729, 1.9400], device='cuda:0')
original loss: 1.504693

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1235, 1.1961, 1.4468, 1.0000, 2.0315, 3.1332], device='cuda:0')
original loss: 1.715031
original loss: 1.753956
Elapsed time in update: 4.364990
exp = baseline_run
 iter =       50/  100000  loss_seg1 = 1.919 loss_seg2 = 2.470 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.476, loss_adv2 = 1.460 loss_D1 = 1.588 loss_D2 = 1.553, val_loss=1.344
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1112, 1.1765, 1.4022, 1.0000, 1.9284, 2.9199], device='cuda:0')
original loss: 1.597939
original loss: 1.338550
Elapsed time in update: 4.371807
exp = baseline_run
 iter =       51/  100000  loss_seg1 = 1.801 loss_seg2 = 1.903 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.496, loss_adv2 = 1.409 loss_D1 = 1.553 loss_D2 = 1.539, val_loss=1.575
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1001, 1.1589, 1.3619, 1.0000, 1.8355, 2.7279], device='cuda:0')
original loss: 1.642591
original lo

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1279, 1.1960, 1.0604, 1.0000, 1.4971, 1.2882], device='cuda:0')
original loss: 1.628758
original loss: 1.403419
Elapsed time in update: 4.383222
exp = baseline_run
 iter =       69/  100000  loss_seg1 = 1.942 loss_seg2 = 2.168 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.570, loss_adv2 = 1.466 loss_D1 = 1.506 loss_D2 = 1.513, val_loss=2.461
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1151, 1.1764, 1.0543, 1.0000, 1.4474, 1.2594], device='cuda:0')
original loss: 1.483490
original loss: 1.190837
Elapsed time in update: 4.377019
exp = baseline_run
 iter =       70/  100000  loss_seg1 = 1.898 loss_seg2 = 1.980 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.583, loss_adv2 = 1.459 loss_D1 = 1.493 loss_D2 = 1.504, val_loss=2.221
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.1036, 12.3110,  1.0489,  1.0000,  1.4026, 12.8339], device='cuda:0')
original loss: 1.548961
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.2056, 1.6125, 1.0082, 1.0000, 1.0671, 1.9793], device='cuda:0')
original loss: 1.456689
original loss: 1.316023
Elapsed time in update: 4.387427
exp = baseline_run
 iter =       88/  100000  loss_seg1 = 1.898 loss_seg2 = 2.152 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.756, loss_adv2 = 1.600 loss_D1 = 1.507 loss_D2 = 1.470, val_loss=1.998
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([8.2950, 1.5513, 1.0073, 7.0000, 7.4230, 1.8814], device='cuda:0')
original loss: 1.444388
original loss: 1.605663
Elapsed time in update: 4.378458
exp = baseline_run
 iter =       89/  100000  loss_seg1 = 1.568 loss_seg2 = 2.014 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.757, loss_adv2 = 1.615 loss_D1 = 1.520 loss_D2 = 1.461, val_loss=2.141
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([12.3655, 14.6731,  1.0066,  1.0000,  1.0544,  1.7932], device='cuda:0')
original loss: 1.455724
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([13.0556, 12.4796,  1.0011,  1.0000,  1.0091, 16.3461], device='cuda:0')
original loss: 1.542651
original loss: 1.567677
Elapsed time in update: 4.376904
exp = baseline_run
 iter =      107/  100000  loss_seg1 = 1.753 loss_seg2 = 2.061 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.779, loss_adv2 = 1.883 loss_D1 = 1.536 loss_D2 = 1.568, val_loss=2.580
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([12.4501,  1.7045,  1.0010,  1.0000,  1.0082,  2.2016], device='cuda:0')
original loss: 1.643464
original loss: 1.730162
Elapsed time in update: 4.384807
exp = baseline_run
 iter =      108/  100000  loss_seg1 = 1.967 loss_seg2 = 2.476 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.729, loss_adv2 = 1.759 loss_D1 = 1.445 loss_D2 = 1.446, val_loss=2.608
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([11.9051,  1.6341,  1.0009, 11.2000, 11.2514, 18.7703], device='cuda:0')
original loss: 1.

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3493, 1.3382, 1.0001, 1.1001, 1.2896, 2.0471], device='cuda:0')
original loss: 1.242567
original loss: 0.954958
Elapsed time in update: 4.381802
exp = baseline_run
 iter =      126/  100000  loss_seg1 = 1.762 loss_seg2 = 1.862 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.762, loss_adv2 = 1.749 loss_D1 = 1.321 loss_D2 = 1.366, val_loss=2.261
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.3144,  1.3044,  1.0001,  1.0901,  1.2606, 17.7965], device='cuda:0')
original loss: 1.360034
original loss: 1.109613
Elapsed time in update: 4.381687
exp = baseline_run
 iter =      127/  100000  loss_seg1 = 1.869 loss_seg2 = 1.805 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.777, loss_adv2 = 1.826 loss_D1 = 1.389 loss_D2 = 1.416, val_loss=2.204
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([13.1806,  1.2739,  1.0001,  1.0811,  1.2346,  2.3881], device='cuda:0')
original loss: 1.351854

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([11.8107,  1.0457,  1.0000,  1.0135,  1.7134, 13.7210], device='cuda:0')
original loss: 1.394611
original loss: 1.129730
Elapsed time in update: 4.367012
exp = baseline_run
 iter =      145/  100000  loss_seg1 = 1.551 loss_seg2 = 1.509 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.939, loss_adv2 = 1.597 loss_D1 = 1.358 loss_D2 = 1.409, val_loss=1.706
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.6185,  1.0411,  1.0000,  1.0122,  1.6421, 13.0489], device='cuda:0')
original loss: 1.481722
original loss: 1.285213
Elapsed time in update: 4.380721
exp = baseline_run
 iter =      146/  100000  loss_seg1 = 1.604 loss_seg2 = 1.533 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.808, loss_adv2 = 1.466 loss_D1 = 1.487 loss_D2 = 1.567, val_loss=2.126
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([10.8967,  1.0370,  1.0000,  1.0109,  1.5779,  1.7777], device='cuda:0')
original loss: 1.

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([9.6587, 1.1297, 1.0000, 1.2343, 1.3288, 1.8335], device='cuda:0')
original loss: 1.537001
original loss: 1.544946
Elapsed time in update: 4.382029
exp = baseline_run
 iter =      164/  100000  loss_seg1 = 1.945 loss_seg2 = 2.144 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.227, loss_adv2 = 2.323 loss_D1 = 1.694 loss_D2 = 1.636, val_loss=1.434
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.3418,  1.1167,  1.0000,  1.2109,  1.2959, 12.2512], device='cuda:0')
original loss: 1.402295
original loss: 1.686939
Elapsed time in update: 4.386219
exp = baseline_run
 iter =      165/  100000  loss_seg1 = 2.022 loss_seg2 = 2.798 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.099, loss_adv2 = 2.250 loss_D1 = 1.628 loss_D2 = 1.545, val_loss=1.771
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3077, 1.1051, 1.0000, 1.1898, 1.2663, 1.6752], device='cuda:0')
original loss: 1.460045
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3769, 1.4641, 1.0000, 1.0316, 1.0444, 1.1126], device='cuda:0')
original loss: 0.927005
original loss: 0.717764
Elapsed time in update: 4.374973
exp = baseline_run
 iter =      183/  100000  loss_seg1 = 1.706 loss_seg2 = 1.633 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.944, loss_adv2 = 1.800 loss_D1 = 1.206 loss_D2 = 1.241, val_loss=1.938
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3392, 1.4177, 1.0000, 1.0285, 1.0400, 1.1013], device='cuda:0')
original loss: 1.219604
original loss: 1.100280
Elapsed time in update: 4.396040
exp = baseline_run
 iter =      184/  100000  loss_seg1 = 1.793 loss_seg2 = 1.802 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.930, loss_adv2 = 1.763 loss_D1 = 1.410 loss_D2 = 1.453, val_loss=2.093
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3053, 1.3759, 1.0000, 1.0256, 1.0360, 1.0912], device='cuda:0')
original loss: 1.389880
original lo

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0509, 1.2321, 1.0000, 1.0043, 1.0060, 2.1990], device='cuda:0')
original loss: 1.367332
original loss: 1.265223
Elapsed time in update: 4.365700
exp = baseline_run
 iter =      202/  100000  loss_seg1 = 1.620 loss_seg2 = 1.719 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.184, loss_adv2 = 2.066 loss_D1 = 1.514 loss_D2 = 1.473, val_loss=1.767
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0458,  1.2089,  1.0000,  1.0038,  1.0054, 14.5536], device='cuda:0')
original loss: 1.283815
original loss: 1.151207
Elapsed time in update: 4.381035
exp = baseline_run
 iter =      203/  100000  loss_seg1 = 1.761 loss_seg2 = 1.824 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.143, loss_adv2 = 2.008 loss_D1 = 1.358 loss_D2 = 1.330, val_loss=1.723
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0412, 1.1880, 1.0000, 1.0035, 1.0049, 1.9712], device='cuda:0')
original loss: 1.300871
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0069, 10.9995,  1.0000,  1.1118,  1.0008, 16.1138], device='cuda:0')
original loss: 1.400007
original loss: 1.307787
Elapsed time in update: 4.379021
exp = baseline_run
 iter =      221/  100000  loss_seg1 = 1.655 loss_seg2 = 1.591 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.069, loss_adv2 = 1.933 loss_D1 = 1.509 loss_D2 = 1.579, val_loss=1.673
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0062,  1.5142,  1.0000,  1.1006,  1.0007, 19.4024], device='cuda:0')
original loss: 1.320414
original loss: 1.222449
Elapsed time in update: 4.381501
exp = baseline_run
 iter =      222/  100000  loss_seg1 = 1.640 loss_seg2 = 1.972 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.956, loss_adv2 = 1.936 loss_D1 = 1.389 loss_D2 = 1.451, val_loss=1.792
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0056, 1.4628, 1.0000, 1.0905, 1.0007, 2.5946], device='cuda:0')
original loss: 1.272337

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0009, 1.0772, 1.0000, 1.0151, 1.2871, 2.1279], device='cuda:0')
original loss: 1.270640
original loss: 1.185338
Elapsed time in update: 4.382470
exp = baseline_run
 iter =      240/  100000  loss_seg1 = 1.746 loss_seg2 = 2.012 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.961, loss_adv2 = 1.913 loss_D1 = 1.295 loss_D2 = 1.280, val_loss=1.648
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([11.2059,  1.0695,  1.0000,  1.0136,  1.2584, 14.1058], device='cuda:0')
original loss: 1.199517
original loss: 1.260395
Elapsed time in update: 4.377037
exp = baseline_run
 iter =      241/  100000  loss_seg1 = 1.492 loss_seg2 = 1.585 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.928, loss_adv2 = 1.885 loss_D1 = 1.438 loss_D2 = 1.463, val_loss=1.615
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.5408, 1.0625, 1.0000, 1.0122, 1.2325, 1.9136], device='cuda:0')
original loss: 1.244776
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0902, 1.8524, 1.0000, 1.0020, 1.0388, 1.1524], device='cuda:0')
original loss: 1.286903
original loss: 1.210907
Elapsed time in update: 4.367110
exp = baseline_run
 iter =      259/  100000  loss_seg1 = 1.591 loss_seg2 = 1.916 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.427, loss_adv2 = 2.492 loss_D1 = 1.472 loss_D2 = 1.476, val_loss=1.376
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0812, 12.3702,  1.0000,  1.0018,  1.0349, 12.1599], device='cuda:0')
original loss: 1.588376
original loss: 1.459960
Elapsed time in update: 4.381633
exp = baseline_run
 iter =      260/  100000  loss_seg1 = 1.854 loss_seg2 = 1.925 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.120, loss_adv2 = 2.276 loss_D1 = 1.587 loss_D2 = 1.570, val_loss=1.524
-------lr_G: 0.000200-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0730, 1.6905, 1.0000, 1.0017, 1.0314, 1.6634], device='cuda:0')
original loss: 1.268358
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0122,  1.9421,  1.0000,  1.0003,  1.5452, 20.5754], device='cuda:0')
original loss: 1.196282
original loss: 1.125270
Elapsed time in update: 4.368680
exp = baseline_run
 iter =      278/  100000  loss_seg1 = 1.499 loss_seg2 = 2.048 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.015, loss_adv2 = 1.932 loss_D1 = 1.393 loss_D2 = 1.428, val_loss=1.630
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0110, 1.8479, 1.0000, 1.0002, 1.4907, 2.7454], device='cuda:0')
original loss: 1.515298
original loss: 1.394263
Elapsed time in update: 4.393720
exp = baseline_run
 iter =      279/  100000  loss_seg1 = 1.774 loss_seg2 = 1.635 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.947, loss_adv2 = 2.101 loss_D1 = 1.468 loss_D2 = 1.434, val_loss=1.986
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0099, 1.7631, 1.0000, 1.0002, 1.4416, 2.5709], device='cuda:0')
original loss: 1.337324
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1542, 1.5381, 1.0000, 1.1883, 1.0737, 1.6753], device='cuda:0')
original loss: 1.115513
original loss: 1.052113
Elapsed time in update: 4.377012
exp = baseline_run
 iter =      297/  100000  loss_seg1 = 1.656 loss_seg2 = 1.550 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.688, loss_adv2 = 1.587 loss_D1 = 1.387 loss_D2 = 1.401, val_loss=2.685
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([12.1712, 14.5898,  1.0000,  1.1695,  1.0663, 15.4543], device='cuda:0')
original loss: 1.267879
original loss: 1.194458
Elapsed time in update: 4.387249
exp = baseline_run
 iter =      298/  100000  loss_seg1 = 1.693 loss_seg2 = 1.620 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.938, loss_adv2 = 1.786 loss_D1 = 1.439 loss_D2 = 1.509, val_loss=1.432
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.6649,  1.9758,  1.0000,  1.1525,  1.0597, 18.8089], device='cuda:0')
original loss: 1.402193

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.1109, 1.3322, 1.0000, 1.0254, 1.0099, 2.1653], device='cuda:0')
original loss: 1.259988
original loss: 1.154985
Elapsed time in update: 4.370892
exp = baseline_run
 iter =      316/  100000  loss_seg1 = 1.720 loss_seg2 = 1.821 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.208, loss_adv2 = 2.131 loss_D1 = 1.287 loss_D2 = 1.278, val_loss=1.594
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([7.6985, 1.2990, 1.0000, 1.0229, 1.0090, 2.0488], device='cuda:0')
original loss: 1.353583
original loss: 1.348245
Elapsed time in update: 4.382389
exp = baseline_run
 iter =      317/  100000  loss_seg1 = 1.564 loss_seg2 = 1.759 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.083, loss_adv2 = 2.039 loss_D1 = 1.390 loss_D2 = 1.363, val_loss=1.550
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0898, 1.2691, 1.0000, 1.0206, 1.0081, 1.9439], device='cuda:0')
original loss: 1.314395
original lo

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0150, 1.8759, 1.0000, 1.0034, 1.0013, 1.5530], device='cuda:0')
original loss: 1.275562
original loss: 1.231075
Elapsed time in update: 4.373024
exp = baseline_run
 iter =      335/  100000  loss_seg1 = 1.495 loss_seg2 = 1.687 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.919, loss_adv2 = 1.841 loss_D1 = 1.329 loss_D2 = 1.384, val_loss=2.058
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([7.0944, 1.7883, 1.0000, 1.0031, 1.0012, 1.4977], device='cuda:0')
original loss: 1.317400
original loss: 1.317146
Elapsed time in update: 4.372676
exp = baseline_run
 iter =      336/  100000  loss_seg1 = 1.310 loss_seg2 = 1.578 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.933, loss_adv2 = 1.865 loss_D1 = 1.351 loss_D2 = 1.402, val_loss=2.316
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([7.0849, 1.7095, 1.0000, 1.0028, 1.0011, 1.4479], device='cuda:0')
original loss: 1.092257
original lo

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.5651, 1.1183, 1.0000, 1.0005, 1.1885, 2.5138], device='cuda:0')
original loss: 1.347046
original loss: 1.303610
Elapsed time in update: 4.368898
exp = baseline_run
 iter =      354/  100000  loss_seg1 = 1.736 loss_seg2 = 1.893 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.904, loss_adv2 = 1.825 loss_D1 = 1.361 loss_D2 = 1.351, val_loss=1.865
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.5086,  1.1065,  1.0000,  1.0004,  1.1696, 20.7370], device='cuda:0')
original loss: 1.312666
original loss: 1.272610
Elapsed time in update: 4.366459
exp = baseline_run
 iter =      355/  100000  loss_seg1 = 1.662 loss_seg2 = 1.662 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.768, loss_adv2 = 1.698 loss_D1 = 1.442 loss_D2 = 1.388, val_loss=1.583
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.4578, 1.0958, 1.0000, 1.0004, 1.1527, 2.7662], device='cuda:0')
original loss: 1.449369
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([14.2145,  1.3703,  1.1695,  1.0001,  1.0255,  3.0111], device='cuda:0')
original loss: 1.320536
original loss: 1.259826
Elapsed time in update: 4.365151
exp = baseline_run
 iter =      373/  100000  loss_seg1 = 1.587 loss_seg2 = 1.589 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.679, loss_adv2 = 1.606 loss_D1 = 1.375 loss_D2 = 1.388, val_loss=1.739
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.9276,  1.3332,  1.1525,  1.0001,  1.0229, 23.8698], device='cuda:0')
original loss: 1.259919
original loss: 1.180789
Elapsed time in update: 4.382067
exp = baseline_run
 iter =      374/  100000  loss_seg1 = 1.509 loss_seg2 = 1.640 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.563, loss_adv2 = 1.439 loss_D1 = 1.399 loss_D2 = 1.428, val_loss=1.659
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.8348, 1.2999, 1.1373, 1.0001, 1.0206, 3.1690], device='cuda:0')
original loss: 1.262532

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3087, 1.5360, 1.0229, 1.0000, 1.0034, 1.9248], device='cuda:0')
original loss: 1.335992
original loss: 1.195184
Elapsed time in update: 4.383669
exp = baseline_run
 iter =      392/  100000  loss_seg1 = 1.506 loss_seg2 = 1.491 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.861, loss_adv2 = 1.956 loss_D1 = 1.335 loss_D2 = 1.378, val_loss=1.577
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.2778, 1.4824, 1.0206, 1.0000, 1.0031, 1.8324], device='cuda:0')
original loss: 1.238317
original loss: 1.147407
Elapsed time in update: 4.367930
exp = baseline_run
 iter =      393/  100000  loss_seg1 = 1.342 loss_seg2 = 1.457 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.799, loss_adv2 = 2.005 loss_D1 = 1.330 loss_D2 = 1.283, val_loss=1.575
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.2500, 14.2392,  1.0185,  1.0000,  1.0028, 16.4438], device='cuda:0')
original loss: 1.643915
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0417, 1.1725, 1.0031, 1.0000, 1.0005, 2.2533], device='cuda:0')
original loss: 1.075234
original loss: 0.896474
Elapsed time in update: 4.386931
exp = baseline_run
 iter =      411/  100000  loss_seg1 = 1.606 loss_seg2 = 1.450 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.049, loss_adv2 = 2.337 loss_D1 = 1.173 loss_D2 = 1.147, val_loss=1.782
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 7.2627,  1.1552,  1.0028, 11.2000, 11.2029,  2.1280], device='cuda:0')
original loss: 1.113193
original loss: 1.185523
Elapsed time in update: 4.377927
exp = baseline_run
 iter =      412/  100000  loss_seg1 = 1.428 loss_seg2 = 1.781 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.984, loss_adv2 = 2.237 loss_D1 = 1.274 loss_D2 = 1.281, val_loss=1.605
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0338, 1.1397, 1.0025, 1.5400, 1.5404, 2.0152], device='cuda:0')
original loss: 1.241354
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 8.5039, 10.5651, 11.2029,  1.0901,  1.0901, 19.3348], device='cuda:0')
original loss: 1.382032
original loss: 1.372633
Elapsed time in update: 4.382909
exp = baseline_run
 iter =      430/  100000  loss_seg1 = 1.609 loss_seg2 = 1.631 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.835, loss_adv2 = 1.636 loss_D1 = 1.448 loss_D2 = 1.572, val_loss=1.681
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.1934,  1.4584,  1.5404,  1.0811,  1.0811, 22.3013], device='cuda:0')
original loss: 1.367242
original loss: 1.306385
Elapsed time in update: 4.369339
exp = baseline_run
 iter =      431/  100000  loss_seg1 = 1.629 loss_seg2 = 1.640 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.675, loss_adv2 = 1.651 loss_D1 = 1.427 loss_D2 = 1.447, val_loss=1.407
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.1740,  1.4125,  1.4863,  1.0729,  1.0730, 24.9712], device='cuda:0')
original loss: 1.

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.4227, 1.8999, 1.4748, 1.0122, 1.0122, 2.9889], device='cuda:0')
original loss: 1.144438
original loss: 1.045021
Elapsed time in update: 4.385083
exp = baseline_run
 iter =      449/  100000  loss_seg1 = 1.421 loss_seg2 = 1.386 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.066, loss_adv2 = 1.982 loss_D1 = 1.267 loss_D2 = 1.285, val_loss=1.751
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.3804,  1.8099,  1.4273,  1.0109, 11.2767,  2.7900], device='cuda:0')
original loss: 1.054974
original loss: 0.937635
Elapsed time in update: 4.384047
exp = baseline_run
 iter =      450/  100000  loss_seg1 = 1.355 loss_seg2 = 1.308 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.614, loss_adv2 = 1.592 loss_D1 = 1.329 loss_D2 = 1.342, val_loss=1.766
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([13.5966, 16.3022,  1.3846,  1.0099,  1.5499, 22.4769], device='cuda:0')
original loss: 1.744984

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.3896,  1.5776,  1.1877,  1.1252,  1.3677, 21.1757], device='cuda:0')
original loss: 1.398829
original loss: 1.408245
Elapsed time in update: 4.384585
exp = baseline_run
 iter =      468/  100000  loss_seg1 = 1.603 loss_seg2 = 1.794 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.124, loss_adv2 = 1.867 loss_D1 = 1.465 loss_D2 = 1.490, val_loss=1.963
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3507, 1.5198, 1.1689, 1.1127, 1.3310, 2.8226], device='cuda:0')
original loss: 1.188706
original loss: 1.205728
Elapsed time in update: 4.378999
exp = baseline_run
 iter =      469/  100000  loss_seg1 = 1.592 loss_seg2 = 1.845 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.095, loss_adv2 = 1.872 loss_D1 = 1.346 loss_D2 = 1.362, val_loss=1.942
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3156, 1.4679, 1.1520, 1.1014, 1.2979, 2.6403], device='cuda:0')
original loss: 1.246768
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0526,  1.3105,  1.0254,  1.0169,  1.0497, 17.0209], device='cuda:0')
original loss: 1.398808
original loss: 1.360728
Elapsed time in update: 4.401989
exp = baseline_run
 iter =      487/  100000  loss_seg1 = 1.832 loss_seg2 = 1.824 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.290, loss_adv2 = 2.263 loss_D1 = 1.467 loss_D2 = 1.421, val_loss=1.693
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0474,  1.2794,  1.0228,  1.0152,  1.0447, 16.0188], device='cuda:0')
original loss: 1.313115
original loss: 1.286727
Elapsed time in update: 4.362235
exp = baseline_run
 iter =      488/  100000  loss_seg1 = 1.444 loss_seg2 = 1.654 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.265, loss_adv2 = 2.367 loss_D1 = 1.406 loss_D2 = 1.386, val_loss=1.768
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0426, 1.2515, 1.0205, 1.0137, 1.0402, 2.1596], device='cuda:0')
original loss: 0.950421

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0071, 12.3583,  1.0034,  1.0023,  1.4462,  1.9539], device='cuda:0')
original loss: 1.417376
original loss: 1.300194
Elapsed time in update: 4.388660
exp = baseline_run
 iter =      506/  100000  loss_seg1 = 1.882 loss_seg2 = 1.926 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.901, loss_adv2 = 1.820 loss_D1 = 1.281 loss_D2 = 1.261, val_loss=1.664
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.0064, 1.6889, 1.0031, 1.0021, 1.4016, 1.8585], device='cuda:0')
original loss: 1.326637
original loss: 1.281200
Elapsed time in update: 4.363652
exp = baseline_run
 iter =      507/  100000  loss_seg1 = 1.780 loss_seg2 = 1.743 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.754, loss_adv2 = 1.659 loss_D1 = 1.412 loss_D2 = 1.400, val_loss=1.870
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.0058,  1.6200,  1.0028,  1.0018,  1.3614, 16.6084], device='cuda:0')
original loss: 1.159789

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.2879,  2.0039,  1.3941,  1.2873,  1.5593, 14.4345], device='cuda:0')
original loss: 1.102074
original loss: 1.053167
Elapsed time in update: 4.367008
exp = baseline_run
 iter =      525/  100000  loss_seg1 = 1.579 loss_seg2 = 1.727 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.062, loss_adv2 = 1.856 loss_D1 = 1.204 loss_D2 = 1.244, val_loss=1.540
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.2591, 1.9035, 1.3547, 1.2586, 1.5033, 1.9559], device='cuda:0')
original loss: 1.197148
original loss: 1.084366
Elapsed time in update: 4.379534
exp = baseline_run
 iter =      526/  100000  loss_seg1 = 1.775 loss_seg2 = 1.792 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.935, loss_adv2 = 1.730 loss_D1 = 1.268 loss_D2 = 1.311, val_loss=1.607
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.2332, 16.8919,  1.3192,  1.2327, 10.1710,  1.8603], device='cuda:0')
original loss: 1.446196

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.2713, 2.5570, 1.0532, 1.0388, 1.0755, 1.6963], device='cuda:0')
original loss: 1.010348
original loss: 0.996528
Elapsed time in update: 4.389883
exp = baseline_run
 iter =      544/  100000  loss_seg1 = 1.137 loss_seg2 = 1.203 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.867, loss_adv2 = 1.603 loss_D1 = 1.314 loss_D2 = 1.414, val_loss=1.912
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.2442, 2.4013, 1.0479, 1.0349, 1.0680, 1.6267], device='cuda:0')
original loss: 1.118580
original loss: 1.038381
Elapsed time in update: 4.376010
exp = baseline_run
 iter =      545/  100000  loss_seg1 = 1.385 loss_seg2 = 1.448 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 1.855, loss_adv2 = 1.807 loss_D1 = 1.343 loss_D2 = 1.344, val_loss=2.011
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.2198,  2.2612,  1.0431,  1.0314,  1.0612, 10.9481], device='cuda:0')
original loss: 0.776476
origi

(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3909, 2.1705, 1.6485, 1.2922, 1.4962, 2.5332], device='cuda:0')
original loss: 1.057904
original loss: 1.030644
Elapsed time in update: 4.384644
exp = baseline_run
 iter =      563/  100000  loss_seg1 = 1.592 loss_seg2 = 1.582 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.061, loss_adv2 = 1.714 loss_D1 = 1.376 loss_D2 = 1.418, val_loss=2.087
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([ 1.3519,  2.0534,  1.5836,  1.2630,  1.4466, 16.6589], device='cuda:0')
original loss: 1.256241
original loss: 1.239696
Elapsed time in update: 4.376462
exp = baseline_run
 iter =      564/  100000  loss_seg1 = 1.746 loss_seg2 = 1.762 loss_me = 0.000  loss_kl = 0.000 loss_adv1 = 2.598, loss_adv2 = 2.600 loss_D1 = 1.435 loss_D2 = 1.358, val_loss=1.692
-------lr_G: 0.000199-------
(1000, 1000)
torch.Size([1, 1000, 1000])
tensor([1.3167, 1.9481, 1.5253, 1.2367, 1.4019, 2.2419], device='cuda:0')
original loss: 1.088271
origi